enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@testing-library/vue@8.*":
    dependencies:
      "@vue/compiler-sfc": "*"
  "@vue/test-utils@2.*":
    dependencies:
      "@vue/compiler-dom": "*"

plugins:
  - checksum: 5e73a1acbb9741fce1e8335e243c9480ea2107b9b4b65ed7643785ddea9e3019aee254a92a853b1cd71023b16fff5b7d3afd5256fe57cd35a54f8785b8c30281
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v4"

supportedArchitectures:
  cpu:
    - x64
    - x86
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.1.1.cjs
